// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int t;
    while (t--)
    {
        int n;
        cin >> n;
        string s;
        cin >> s;
        vector<char> v;
        char c = s[0];
        for (int i = 1; i < n; i++)
        {
            if (s[i] == c)
            {
                v.push_back(s[i]);
                c = s[i + 1];
                i++;
                // cout<<c<<" ";
            }
        }
        // cout<<endl;
        for (auto i : v)
        {
            cout << i;
        }
        cout << endl;
    }

    return 0;
}