// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int t;
    cin >> t;
    while (t--)
    {
        long long n, b;
        cin >> n;
        cin >> b;
        string s;
        cin >> s;
        if (n < b)
        {
            cout << "NO" << endl;
            continue;
        }
        long long val = 0;
        map<char, long long> mp;
        for (auto x : s)
        {
            mp[x]++;
        }
        for (auto [x, y] : mp)
        {
            val += (y % 2);
        }
        val--;
        if (b < val)
        {
            cout << "NO" << endl;
            continue;
        }
        cout << "YES" << endl;
    }

    return 0;
}