//This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include<bits/stdc++.h>
using namespace std;
int main()
{
    int t;
    cin>>t;
    while (t--)
    {
        int n,t;
        cin>>n;
        cin>>t;
        vector<int> a(n);
        for (int i = 0; i < n; i++)
        {
            cin>>a[i];
        }
        if(t==4){
            int tr = t, solve = 2;
            for (int i = 0; i < n; i++)
            {
                if (a[i]%4==0)
                {
                    tr = 0;
                    break;
                }else{
                    if (tr>t-a[i]%t)
                    {
                        tr = t-a[i]%t;
                    }
                }
            }
            for (int i = 0; i < n; i++)
            {
                if (a[i]%2==0)
                {
                    solve=max(solve-1,0);
                }
                
            }
            cout<<min(solve,tr)<<endl;
            
        }else{
            int tr =t;
            for (int i = 0; i < n; i++)
            {
                if (a[i]%t==0)  
                {
                    tr = 0;
                    break;
                }else{
                    if(tr>t-a[i]%t){
                        tr = t - a[i] % t;
                    }
                }
                
            }
            
            cout<<tr<<endl;
        }
        
    }
    

return 0;
}