// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
void solve()
{
    int a, b;
    cin >> a;
    cin >> b;
    string s;
    cin>>s;
    int solve = 0;
    for (int i = 0; i <= a; i++)
    {
        if (s[i] == 'B')
        {
            solve++;
            i += b - 1;
        }
    }
    cout << solve << endl;
}
int main()
{
    int t;
    cin >> t;
    while (t--)
    {
        solve();
    }
    return 0;
}