//This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include<bits/stdc++.h>
using namespace std;
void solve(){
    long long n,x;
    cin>>n>>x;
    vector<long long>a(n);
    for (long long i = 0; i < n; i++)
    {
        cin>>a[i];
    }
    long long l=1,r=INT_MAX;
    long long ans = INT_MAX;
    while(l<=r){
        long long mid = (r-l)/2+l;
        long long res = 0;
        for(long long &i: a){
            if(mid>i){
                res+=(mid-i);
            }
        }
        if(res<=x){
            ans = mid;
            l=mid+1;
        }else{
            r=mid-1;
        }
    }
    cout<<ans<<endl;
}
int main()
{
int t;
cin>>t;
while(t--){
    solve();
}
return 0;
}