// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int t;
    cin >> t;
    while (t--)
    {
        int m;
        cin >> m;
        vector<int> ar;
        long long jog = 0;
        int count = 0;
        for (int i = 0; i < m; i++)
        {
            int y;
            cin >> y;
            if (y == 1)
            {
                count++;
            }
            jog += y;
            ar.push_back(y);
        }
        if (jog - m >= count && m > 1)
            cout << "YES\n";
        else
            cout << "NO\n";
    }
    return 0;
}